# Generated by Django 5.0.7 on 2024-08-04 02:28

import django.db.models.deletion
import gestionPedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_art', models.IntegerField(default=0, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50, verbose_name='LA DIRECCION DE CLIENTE')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('entregado', models.BooleanField()),
                ('codigo_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.articulos')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.clientes')),
            ],
        ),
    ]
