# Generated by Django 5.0.7 on 2024-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='DIRECCION DEL CLIENTE'),
        ),
    ]
