# Generated by Django 5.0.7 on 2024-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
