# Generated by Django 5.0.7 on 2024-08-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='DIRECCION DEL CLIENTE'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.articulos', to_field='codigo_art'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.clientes', to_field='rut'),
        ),
    ]
